repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3          
    hooks:
      - id: gitleaks
        args:
          #only scan what’s staged for commit
          - --staged       
          #hide secret values in output
          - --redact