name: Secret Scan (Gitleaks)

#workflow runs:
# - on every push to 'main'
# - on every pull request (targeting any branch)
# - on a weekly schedule: Mondays at 03:00 UTC
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 3 * * 1'

permissions:
  #required to checkout code
  contents: read
  #allows the action to read its own metadata
  actions: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    #pulls full repo history so gitleaks can scan diffs across all commits if needed
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #run Gitleaks using the built-in defaults and required GITHUB_TOKEN
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #combined validation + findings check: treats missing SARIF as no leaks
    - name: Determine if leaks were found
      id: findings
      run: |
        echo "found=false" >> $GITHUB_OUTPUT
        SARIF_FILE="gitleaks-results.sarif"
        if [ -f "$SARIF_FILE" ]; then
          if jq '.runs[].results | length > 0' "$SARIF_FILE" | grep -q '^true$'; then
            echo "Secrets/leaks detected!"
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "No secrets found in SARIF."
          fi
        else
          echo "No SARIF file; assuming no leaks."
        fi

    #only upload the SARIF report as an artifact if findings were detected
    - name: Upload report if leaks were found
      if: steps.findings.outputs.found == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-results.sarif
