name: Stock Data Download

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  execute_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: 'GitHub Actions/Stock Download'

      - name: Run py script
        run: python3 stock_download.py
        working-directory: 'GitHub Actions/Stock Download'