name: Stock Data Download

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  execute_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          cd GitHub\ Actions/Stock\ Download
          pip install -r requirements.txt

      - name: Run py script
        run: |
          cd GitHub\ Actions/Stock\ Download
          python3 stock_download.py
