name: Stock Data Download

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  execute_python_script:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install Dependencies
      run: pip install -r requirements.txt
      working-directory: 'GitHub Actions/Stock Download'
    
    - name: Run Py Script
      run: python3 stock_download.py
      working-directory: 'GitHub Actions/Stock Download'

    - name: Commit and Push Changes
      run:  |
        git config --global user.name ${{ secrets.USERNAME }}
        git config --global user.email ${{ secrets.EMAIL }}
        git add .
        git commit -m "Update aapl_data.csv"
        git push
      working-directory: 'GitHub Actions/Stock Download'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}