name: Trivy Security Scan for Python 3.13-slim

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Scan Python 3.13-slim with Trivy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p "GitHub Actions/Trivy Automation"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python:3.13-slim'
          format: 'json'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: "GitHub Actions/Trivy Automation/scan-results.json"

      - name: Display results
        run: cat "GitHub Actions/Trivy Automation/scan-results.json"

      - name: Push results back to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "GitHub Actions/Trivy Automation/scan-results.json"
          git commit -m "Add Trivy scan results"
          git push origin HEAD:main