name: Trivy Security Scan for NGINX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Scan nginx:latest with Trivy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Pre-download Vulnerability Database
        run: |
          mkdir -p /tmp/trivy-cache
          trivy --cache-dir /tmp/trivy-cache --download-db-only

      - name: Run Trivy vulnerability scanner
        run: |
          DATE=$(date +"%m.%d.%Y")
          mkdir -p "GitHub Actions/Trivy Automation"
          OUTPUT_FILE="GitHub Actions/Trivy Automation/scan-results-${DATE}.json"
          trivy image --format json --ignore-unfixed --scanners vuln --severity CRITICAL,HIGH,MEDIUM,LOW -o "$OUTPUT_FILE" nginx:latest

      - name: Display Trivy scan results
        run: |
          DATE=$(date +"%m.%d.%Y")
          cat "GitHub Actions/Trivy Automation/scan-results-${DATE}.json"

      - name: Push results back to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +"%m.%d.%Y")
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "GitHub Actions/Trivy Automation/scan-results-${DATE}.json"
          git commit -m "Add Trivy scan results (${DATE})"
          git push origin HEAD:main