name: Trivy Security Scan for NGINX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Scan nginx:latest with Trivy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p "GitHub Actions/Trivy Automation"

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.57.0

      - name: Clear Trivy cache
        run: trivy --reset

      - name: Update Trivy database
        run: trivy --download-db-only

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx:latest'
          format: 'json'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          output: "GitHub Actions/Trivy Automation/scan-results.json"

      - name: Add date to scan results
        run: |
          DATE=$(date +"%m.%d.%Y")
          TMP_FILE="GitHub Actions/Trivy Automation/scan-results.tmp.json"
          jq --arg date "$DATE" '. + {scanDate: $date}' "GitHub Actions/Trivy Automation/scan-results.json" > $TMP_FILE
          mv $TMP_FILE "GitHub Actions/Trivy Automation/scan-results.json"

      - name: Display Trivy scan results
        run: cat "GitHub Actions/Trivy Automation/scan-results.json"

      - name: Push results back to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "GitHub Actions/Trivy Automation/scan-results.json"
          git commit -m "Add Trivy scan results"
          git push origin HEAD:main